title: 24 lutego
description: Jak stworzyć stronę w just-the-docs
theme: just-the-docs

url: https://ewapajak17.github.io/JustTheDocs

aux_links:
  Template Repository: https://github.com/ewapajak17/JustTheDocs
